name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - 'steelbrain/**'

permissions:
  contents: read

jobs:
  test:
    name: Test (${{ matrix.platform }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-amd64
            runner: windows-2025
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: dtolnay/rust-toolchain@4360b52568e2003a75bf9bc1d59f33a8e3fc893c # stable
        with:
          components: clippy, rustfmt
          targets: ${{ matrix.target }}

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run Clippy
        env:
          TARGET: ${{ matrix.target }}
        run: cargo clippy --locked --all-targets --target "$env:TARGET" -- -D warnings

      - name: Run tests
        env:
          TARGET: ${{ matrix.target }}
        run: cargo test --locked --target "$env:TARGET"

      - name: Build release binary
        env:
          TARGET: ${{ matrix.target }}
        run: cargo build --locked --release --target "$env:TARGET"
